FROM node:14.16.0-alpine

RUN mkdir -p /client

COPY ./package.json ./client

WORKDIR /client

RUN npm install
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm install -g serve
