version: '3'
services:
  client-dev:
    image: client-dev:latest
    build: "./client/Dockerfile.dev"
    networks:
      my-net:
    ports:
      - "3000:3000"
    container_name: 'client-dev'

  api-dev:
    image: api-dev:latest
    build: "./server/Dockerfile.dev"
    networks:
      my-net:
    ports:
      - "5000:5000"
    container_name: 'api-dev'

  mongo:
    image: mongo:latest
    networks:
      my-net:
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

networks:
  my-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
